#!/bin/sh
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=1:mem=8GB:tmpspace=900GB


# Serial

module load intel-suite
module load fftw/3.1.1-double
export NETCDF_VERSION=4.3.3                
module load netcdf/$NETCDF_VERSION  
                                              

pbsdsh2 cp ${WORK}/saves/1/QG/QG_new.nc $TMPDIR
pbsexec ${WORK}/CODE/BUILD/qg2 -in QG_new.nc -out QG_new.nc
pbsdsh2 cp ${TMPDIR}/* ${WORK}/saves/1/QG
