#!/bin/sh
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=1:mem=20GB:tmpspace=900GB


# Serial

module load intel-suite
module load fftw
export NETCDF_VERSION=4.3.3                
module load netcdf/$NETCDF_VERSION  
module load mpi      

cp ${WORK}/saves/1/QG/NEW_FIELD/QG_new.nc ${WORK}/saves/1/QG/NEW_FIELD/QG_ave_new.nc ${TMPDIR} 
${WORK}/TEST_CODE/BUILD/create_bins
pbsdsh2 cp ${TMPDIR}/full_PV_bins_trajectories_boundaries.nc ${WORK}/saves/1/TRAJ
